package spring.ladybug.ladybugapp.pojos;
// Generated Jan 17, 2020 7:52:18 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BugDtls generated by hbm2java
 */
@Entity
@Table(name = "bug_dtls", catalog = "ladybug_main")
public class BugDtls implements java.io.Serializable {

	private String bugId;
	private Employee employee;
	private Project projects;
	private String bugName;
	private String bugDesc;
	private Date bugStart;
	private Date bugEnd;
	private String bugPriority;
	private String bugAssignee;
	private String bugStatus;
	private String bugMgrId;

	public BugDtls() {
	}

	public BugDtls(String bugId, Employee employee, String bugName, String bugDesc) {
		this.bugId = bugId;
		this.employee = employee;
		this.bugName = bugName;
		this.bugDesc = bugDesc;
	}

	public BugDtls(String bugId, Employee employee, Project projects, String bugName, String bugDesc, Date bugStart,
			Date bugEnd, String bugPriority, String bugAssignee, String bugStatus, String bugMgrId) {
		this.bugId = bugId;
		this.employee = employee;
		this.projects = projects;
		this.bugName = bugName;
		this.bugDesc = bugDesc;
		this.bugStart = bugStart;
		this.bugEnd = bugEnd;
		this.bugPriority = bugPriority;
		this.bugAssignee = bugAssignee;
		this.bugStatus = bugStatus;
		this.bugMgrId = bugMgrId;
	}

	@Id

	@Column(name = "bug_id", unique = true, nullable = false, length = 45)
	public String getBugId() {
		return this.bugId;
	}

	public void setBugId(String bugId) {
		this.bugId = bugId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bug_by_emp_id", nullable = false)
	public Employee getEmployees() {
		return this.employee;
	}

	public void setEmployees(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bug_project_id")
	public Project getProjects() {
		return this.projects;
	}

	public void setProjects(Project projects) {
		this.projects = projects;
	}

	@Column(name = "bug_name", nullable = false, length = 45)
	public String getBugName() {
		return this.bugName;
	}

	public void setBugName(String bugName) {
		this.bugName = bugName;
	}

	@Column(name = "bug_desc", nullable = false, length = 250)
	public String getBugDesc() {
		return this.bugDesc;
	}

	public void setBugDesc(String bugDesc) {
		this.bugDesc = bugDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bug_start", length = 19)
	public Date getBugStart() {
		return this.bugStart;
	}

	public void setBugStart(Date bugStart) {
		this.bugStart = bugStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bug_end", length = 19)
	public Date getBugEnd() {
		return this.bugEnd;
	}

	public void setBugEnd(Date bugEnd) {
		this.bugEnd = bugEnd;
	}

	@Column(name = "bug_priority", length = 45)
	public String getBugPriority() {
		return this.bugPriority;
	}

	public void setBugPriority(String bugPriority) {
		this.bugPriority = bugPriority;
	}

	@Column(name = "bug_assignee", length = 45)
	public String getBugAssignee() {
		return this.bugAssignee;
	}

	public void setBugAssignee(String bugAssignee) {
		this.bugAssignee = bugAssignee;
	}

	@Column(name = "bug_status", length = 45)
	public String getBugStatus() {
		return this.bugStatus;
	}

	public void setBugStatus(String bugStatus) {
		this.bugStatus = bugStatus;
	}

	@Column(name = "bug_mgr_id", length = 45)
	public String getBugMgrId() {
		return this.bugMgrId;
	}

	public void setBugMgrId(String bugMgrId) {
		this.bugMgrId = bugMgrId;
	}

}
