package spring.ladybug.ladybugapp.pojos;
// Generated 19 Jan, 2020 1:05:57 PM by Hibernate Tools 5.0.6.Final

import java.time.LocalDate;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employees", catalog = "ladybug_app_main")
public class Employee implements java.io.Serializable {

	private Integer empId;
	private Employee emp;
	private String firstName;
	private String lastName;
	private LocalDate createdOn;
	private String userName;
	private Set<Employee> employees = new HashSet<>();
	private Set<BugDtls> bugDtls = new HashSet<>();
	private Login login;
	private Set<Project> projects = new HashSet<>();

	public Employee() {
	}

	public Employee(Employee emp, String firstName, String lastName, LocalDate createdOn, String userName,
			Set<Employee> employees, Set<BugDtls> bugDtls, Login login, Set<Project> projects) {
		this.emp = emp;
		this.firstName = firstName;
		this.lastName = lastName;
		this.createdOn = createdOn;
		this.userName = userName;
		this.employees = employees;
		this.bugDtls = bugDtls;
		this.login = login;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "emp_id", unique = true, nullable = false)
	public Integer getEmpId() {
		return this.empId;
	}

	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mgr_id")
	public Employee getEmp() {
		return this.emp;
	}

	public void setEmp(Employee employees) {
		this.emp = employees;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	//@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", length = 19)
	public LocalDate getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(LocalDate createdOn) {
		this.createdOn = createdOn;
	}

	@Column(name = "user_name", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emp")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emp")
	public Set<BugDtls> getBugDtls() {
		return this.bugDtls;
	}

	public void setBugDtls(Set<BugDtls> bugDtls) {
		this.bugDtls = bugDtls;
	}
	
	
	@JsonIgnore
	@OneToOne(mappedBy = "emp")
	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "emp_project_relation", catalog = "ladybug_app_main", joinColumns = {
			@JoinColumn(name = "e_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "proj_id", nullable = false, updatable = false) })
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
