package spring.ladybug.ladybugapp.pojos;
// Generated Jan 17, 2020 7:52:18 PM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Projects generated by hbm2java
 */
@Entity
@Table(name = "projects", catalog = "ladybug_main")
public class Project implements java.io.Serializable {

	private String projectId;
	private String projectName;
	private String projectDesc;
	private String projectMgr;
	private Set<BugDtls> bugDtlses = new HashSet<>();
	private Set<Employee> employeeses = new HashSet<>(0);

	public Project() {
	}

	public Project(String projectId, String projectName) {
		this.projectId = projectId;
		this.projectName = projectName;
	}

	public Project(String projectId, String projectName, String projectDesc, String projectMgr, Set<BugDtls> bugDtlses,
			Set<Employee> employeeses) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.projectDesc = projectDesc;
		this.projectMgr = projectMgr;
		this.bugDtlses = bugDtlses;
		this.employeeses = employeeses;
	}

	@Id

	@Column(name = "project_id", unique = true, nullable = false, length = 45)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	@Column(name = "project_name", nullable = false, length = 45)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "project_desc", length = 45)
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@Column(name = "project_mgr", length = 45)
	public String getProjectMgr() {
		return this.projectMgr;
	}

	public void setProjectMgr(String projectMgr) {
		this.projectMgr = projectMgr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projects")
	public Set<BugDtls> getBugDtlses() {
		return this.bugDtlses;
	}

	public void setBugDtlses(Set<BugDtls> bugDtlses) {
		this.bugDtlses = bugDtlses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "emp_project_relation", catalog = "ladybug_main", joinColumns = {
			@JoinColumn(name = "proj_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "e_id", nullable = false, updatable = false) })
	public Set<Employee> getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set<Employee> employeeses) {
		this.employeeses = employeeses;
	}

}
